# Generated by Django 3.0.4 on 2020-03-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
